In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [16]:
df=pd.read_csv('/content/Market_Basket_Optimisation.csv')
df.head()

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

DATA PREPROCESSING

In [17]:
#Understanding the data matrix
df.shape

(7500, 20)

In [18]:
df.isnull().sum()

shrimp                  0
almonds              1754
avocado              3112
vegetables mix       4156
green grapes         4972
whole weat flour     5637
yams                 6132
cottage cheese       6520
energy drink         6847
tomato juice         7106
low fat yogurt       7245
green tea            7347
honey                7414
salad                7454
mineral water        7476
salmon               7493
antioxydant juice    7497
frozen smoothie      7497
spinach              7498
olive oil            7500
dtype: int64

In [23]:
# Perform one-hot encoding
df_encoded = pd.get_dummies(df, columns=["shrimp","almonds", "avocado","vegetables mix","green grapes","whole weat flour","yams","cottage cheese","energy drink","tomato juice","low fat yogurt","green tea","honey","salad","mineral water","salmon","antioxydant juice","frozen smoothie","spinach","olive oil"])

print(df_encoded)

      shrimp_almonds  shrimp_antioxydant juice  shrimp_asparagus  \
0                  0                         0                 0
1                  0                         0                 0
2                  0                         0                 0
3                  0                         0                 0
4                  0                         0                 0
...              ...                       ...               ...
7495               0                         0                 0
7496               0                         0                 0
7497               0                         0                 0
7498               0                         0                 0
7499               0                         0                 0

      shrimp_avocado  shrimp_babies food  shrimp_bacon  shrimp_barbecue sauce  \
0                  0                   0             0                      0
1                  0                   0             0                      0
2                  0                   0             0                      0
3                  0                   0             0                      0
4                  0                   0             0                      0
...              ...                 ...           ...                    ...
7495               0                   0             0                      0
7496               0                   0             0                      0
7497               0                   0             0                      0
7498               0                   0             0                      0
7499               0                   0             0                      0

      shrimp_black tea  shrimp_blueberries  shrimp_body spray  ...  \
0                    0                   0                  0  ...
1                    0                   0                  0  ...
2                    0                   0                  0  ...
3                    0                   0                  0  ...
4                    0                   0                  0  ...
...                ...                 ...                ...  ...
7495                 0                   0                  0  ...
7496                 0                   0                  0  ...
7497                 0                   0                  0  ...
7498                 0                   0                  0  ...
7499                 0                   0                  0  ...

      salmon_frozen smoothie  salmon_magazines  salmon_protein bar  \
0                          0                 0                   0
1                          0                 0                   0
2                          0                 0                   0
3                          0                 0                   0
4                          0                 0                   0
...                      ...               ...                 ...
7495                       0                 0                   0
7496                       0                 0                   0
7497                       0                 0                   0
7498                       0                 0                   0
7499                       0                 0                   0

      salmon_sparkling water  antioxydant juice_french fries  \
0                          0                               0
1                          0                               0
2                          0                               0
3                          0                               0
4                          0                               0
...                      ...                             ...
7495                       0                               0
7496                       0                               0
7497                       0                               0
7498                       0                               0
7499                       0                               0

      antioxydant juice_frozen smoothie  frozen smoothie_protein bar  \
0                                     0                            0
1                                     0                            0
2                                     0                            0
3                                     0                            0
4                                     0                            0
...                                 ...                          ...
7495                                  0                            0
7496                                  0                            0
7497                                  0                            0
7498                                  0                            0
7499                                  0                            0

      frozen smoothie_spinach  spinach_cereals  spinach_mayonnaise
0                           0                0                   0
1                           0                0                   0
2                           0                0                   0
3                           0                0                   0
4                           0                0                   0
...                       ...              ...                 ...
7495                        0                0                   0
7496                        0                0                   0
7497                        0                0                   0
7498                        0                0                   0
7499                        0                0                   0

[7500 rows x 1262 columns]